project:
  type: website
  output-dir: docs

website:
  title: "Card & DeVasto"
  page-navigation: true
  reader-mode: true
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Webtext demo
      - href: z01_proposal.qmd
        text: Proposal
    right: 
      - icon: github
        href: https://danieljcard1.github.io/card-devasto_kairos-submission/
        aria-label: Github

  sidebar:
    contents: 
      - article/a01_intro.qmd
      - article/a02_background.qmd
      - article/a03_artifacts.qmd

format:
  html:
    theme: 
      light: materia
      dark: cyborg
    css: styles.css
    toc: true
    embed-resources: true



